spring:
  application:
    name: yu-ai-agent
    mcp:
      client:
        stdio:
        servers-configuration: "classpath:mcp-server.json"
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-5470d073c94f45d3aff9b9703f6a8c81}
      chat:
        options:
          model: qwen-plus
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.itzhiqin.yuaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI key
search-api:
  api-key: CdoM1N2eaYoTQYh92YnnjL7z
kind: Application